apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  selector:
    app: auth-service-app
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 80 
      nodePort: 30091