apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dynamic-routing-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~ ^/dynamic/(.*) {
          set $dynamic_service_name $1;
          access_by_lua_block {
              local http = require "resty.http"
              local httpc = http.new()
              local res, err = httpc:request_uri("http://auth-service.default.svc.cluster.local/dynamic/" .. ngx.var.dynamic_service_name, {
                  method = "GET",
                  keepalive_timeout = 60000,
                  keepalive_pool = 10
              })
              
              if not res then
                  ngx.log(ngx.ERR, "failed to request the service: ", err)
                  return ngx.exit(500)
              end
              
              if res.status == 200 then
                  ngx.var.service_name = res.body
              else
                  ngx.log(ngx.NOTICE, "the key didn't exist in the Redis DB")
                  ngx.status = 404
                  ngx.header.content_type = "text/plain"
                  ngx.say("the key didn't exist in the Redis DB")
                  return ngx.exit(404)
              end
          }
          proxy_pass http://$service_name.default.svc.cluster.local;
      }
spec:
  rules:
    - host: kubernetes.docker.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
